on: 
  release:
  workflow_dispatch:
jobs:
  gaglia-2020-0813:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Dataverse 
        uses: IQSS/dataverse-uploader@v1.3
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: 10.7910/DVN/HOFPZJ
          GITHUB_DIR: gaglia-2020-0813
          DELETE: False
          PUBLISH: False 
  gaglia-2020-gemm-lung:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Dataverse 
        uses: IQSS/dataverse-uploader@v1.3
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: 10.7910/DVN/FO1M99
          GITHUB_DIR: gaglia-2020-gemm-lung 
          DELETE: False
          PUBLISH: False 
  lin-2021-viz-97:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Dataverse 
        uses: IQSS/dataverse-uploader@v1.3
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: 10.7910/DVN/BAPIVM
          GITHUB_DIR: lin-2021-viz-97
          DELETE: False
          PUBLISH: False 
  lin-2021-reg_96_97: 
    runs-on: ubuntu-latest
    steps:
      - name: Send to Dataverse 
        uses: IQSS/dataverse-uploader@v1.3
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: 10.7910/DVN/RAIJKQ
          GITHUB_DIR: lin-2021-reg_96_97
          DELETE: False
          PUBLISH: False 
